name: Fly Deploy
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:

      # - name: Install Fly CLI
      #   run: |
      #     curl -L https://fly.io/install.sh | sh
      #     export PATH=$HOME/.fly/bin:$PATH

      # - name: Verify Fly CLI Installation
      #   run: fly --version

      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          if [[ ${{ github.ref_name }} == "main" ]]; then
            flyctl deploy --config fly.toml --app readydent
          elif [[ ${{ github.ref_name }} == "dev" ]]; then
            flyctl deploy --config fly-staging.toml --app app-staging1
          fi
        
        #flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
